apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-simple-staging

images:
- name: dc88/kargo-demo
  newName: dc88/kargo-demo
  newTag: guestbook-v0.0.1
